version: '3.8'
services:
  web:
    build: ./transport-marketplace/apps/web
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    deploy:
      replicas: 3

  api:
    build: ./transport-marketplace/apps/api
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    ports:
      - "3001:3001"
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

networks:
  default:
    external: false
