import sharp from 'sharp';
// ...import MinIO SDK...

export async function uploadToMinio(file: Express.Multer.File) {
  // ...upload original file to MinIO...
  // ...return URLs for original, thumbnail, preview...
}

export async function generateThumbnails(file: Express.Multer.File) {
  // ...sharp: 200x200 thumbnail, 800x600 preview...
  // ...upload thumbnails to MinIO...
}
